version: 1.0.{build}
image: Visual Studio 2015
install:
  - ps: >-
      Invoke-WebRequest -Uri "https://download.virtualbox.org/virtualbox/6.1.18/VirtualBox-6.1.18-142142-Win.exe" -OutFile "VirtualBoxSetup.exe";
      .\VirtualBoxSetup.exe -extract -path Out;
      dir Out;
