version: 1.0.{build}
image: Visual Studio 2015
build_script:
  - ps: >-
      Invoke-WebRequest -Uri "https://download.virtualbox.org/virtualbox/6.1.18/VirtualBox-6.1.18-142142-Win.exe" -OutFile "VirtualBoxSetup.exe";
      $outpath = (Get-Item .).FullName + "\Out";
      mkdir $outpath;
      .\VirtualBoxSetup.exe -extract -path $outpath | Out-Null;
      dir $outpath;
